on:
  push:
    branches:
      - master
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: sudo apt install asymptote
    - run: pip install -r requirements.txt
    - run: ./imagecachesync.sh
    # build script invokes asymptote, for whatever reason a window is needed for 3d drawings
    - uses: GabrielBB/xvfb-action@v1.5
      with:
        run: python3 build.py
    - uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages-asdf
        folder: html
